baseURL = "https://mcaneff.github.io/podcasts-to-books/"
title = "Podcast To Books"
theme = "PaperMod"
enableRobotsTXT = true

[params]
  ShowReadingTime = true
  mainsections = ["chris-williamson", "lex-fridman", "joe-rogan"]
  ShowRssButtonInSectionTermList = false
  ShowPostNavLinks = true

[services]
  [services.googleAnalytics]
    id = "G-X7GMKLV284"

[outputs]
  home = [ "HTML", "RSS", "JSON", "Sitemap" ]

[[menu.main]]
  name = "Chris Williamson"
  url = "/chris-williamson/"
  weight = 1

[[menu.main]]
  name = "Lex Fridman"
  url = "/lex-fridman/"
  weight = 2

[[menu.main]]
  name = "Joe Rogan"
  url = "/joe-rogan/"
  weight = 3

  [[menu.main]]
  name = "Curt Jaimungal"
  url = "/curt-jaimungal/"
  weight = 4

[[menu.main]]
  name = "Search"
  url = "/search"
  weight = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
name = "More..."
url = "/more"
weight = 500
identifier = "more"
